import mongoose from "mongoose";

const messageSchema = new mongoose.Schema(
  {
    role: {
      type: String,
      enum: ["user", "assistant"],
      required: true,
    },
    content: {
      type: String,
      required: true,
    },
  },
  { _id: false, timestamps: true }
);

const testChatSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    // A unique ID generated by the frontend for this specific conversation
    conversationId: {
      type: String,
      required: true,
      unique: true,
    },
    activeStep: {
      type: String,
      required: true,
    },
    // The entire conversation history
    messages: [messageSchema],
  },
  { timestamps: true }
);

testChatSchema.index({ userId: 1, conversationId: 1 });

const TestChat =
  mongoose.models.TestChat || mongoose.model("TestChat", testChatSchema);

export default TestChat;
